version: '3.8'
services:
  app:
    container_name: frontend
    image: nestjs-api:1.0.0
    build:
      context: .
      dockerfile: DOCKERFILE
    ports:
      - "3000:3000"
    networks:
      - frontend-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
  frontend-network: